### ISSUE TITLE
Pass multiple arguments and do not concatenate

### ISSUE THREAD

**Issue by KES777** [preaction/Log-Any-Adapter-Log4perl#4]
Log4perl support multiple arguments to their logging functions and has concatenate them by its own.

Please do not concatenate. This break Log::Log4perl::Appender::DBI which expect multiple arguments

```
Log::Any::Adapter->set('Log4perl');

$m->log->warn( 'param', 'param2', 'param3' );
```

Also it make impossible to configure any adapter with 'warp_message'

```
log4perl.appender.LF_MasonRequest.warp_message             = MasonHandler::logmsg_filter
log4perl.appender.LF_MasonRequest.layout                   = FallbackLayout
log4perl.appender.LF_MasonRequest.layout.chain                   = PatternLayout
log4perl.appender.LF_MasonRequest.layout.chain.ConversionPattern = %r >> %p >> %m{indent=1} >> %c >> at %F line %L%n
```

The message come broken to 'MasonHandler::logmsg_filter' function.

The adapter to logging system must decide how to delive messsages to logging system. And the Log::Any::Proxy must pass them ASIS unless it has special configuration options

**Comment by preaction** [comment]
If it's really a problem with Log::Any::Proxy, then this is not the correct place for this issue. Log::Any::Proxy has always produced a single string to give to adapters, so for backwards compatibility reasons I can't change it.

The structured logging added in Log-Any v1.700 and now supported by Log-Any-Adapter-Log4perl v0.09 does pass in all of the fields to the logger, so that may fix this problem. Otherwise, the only fix is to create a custom proxy that does what you want.
